// <auto-generated />
using System;
using HotelRoomOrdering.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelRoomOrdering.Api.Data.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    [Migration("20260415194220_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CategoryIcon")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("Categories", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.City", b =>
                {
                    b.Property<long>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CityId"));

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("StateName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CityId");

                    b.HasIndex("CityCode")
                        .IsUnique();

                    b.ToTable("Cities", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.GuestSession", b =>
                {
                    b.Property<Guid>("GuestSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OtpSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("GuestSessionId");

                    b.HasIndex("HotelId");

                    b.HasIndex("OtpSessionId");

                    b.ToTable("GuestSessions", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Hotel", b =>
                {
                    b.Property<long>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("HotelId"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("KitchenId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int>("RoomCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("HotelId");

                    b.HasIndex("CityId");

                    b.HasIndex("HotelCode")
                        .IsUnique();

                    b.HasIndex("KitchenId");

                    b.ToTable("Hotels", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.HotelMenuItem", b =>
                {
                    b.Property<long>("HotelMenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("HotelMenuItemId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("InventoryQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("HotelMenuItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("HotelId", "ItemId")
                        .IsUnique();

                    b.ToTable("HotelMenuItems", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Item", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemId"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVeg")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("Items", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Kitchen", b =>
                {
                    b.Property<long>("KitchenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KitchenId"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KitchenCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LoginUsername")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KitchenId");

                    b.HasIndex("CityId");

                    b.HasIndex("KitchenCode")
                        .IsUnique();

                    b.HasIndex("LoginUsername")
                        .IsUnique();

                    b.ToTable("Kitchens", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.KitchenItemAvailability", b =>
                {
                    b.Property<long>("KitchenItemAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KitchenItemAvailabilityId"));

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EffectivePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("KitchenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("KitchenItemAvailabilityId");

                    b.HasIndex("ItemId");

                    b.HasIndex("KitchenId", "ItemId")
                        .IsUnique();

                    b.ToTable("KitchenItemAvailability", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderId"));

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("GuestNotes")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint");

                    b.Property<long>("KitchenId")
                        .HasColumnType("bigint");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<byte>("OrderStatus")
                        .HasColumnType("smallint");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("smallint");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("PreparingAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReadyAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("SubTotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WebhookVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("WebhookVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("HotelId");

                    b.HasIndex("KitchenId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.OrderLine", b =>
                {
                    b.Property<long>("OrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderLineId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVegSnapshot")
                        .HasColumnType("boolean");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemSnapshotName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("OrderLineId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.OrderStatusHistory", b =>
                {
                    b.Property<long>("OrderStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderStatusHistoryId"));

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<byte>("NewStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("PreviousStatus")
                        .HasColumnType("smallint");

                    b.HasKey("OrderStatusHistoryId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistory", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.OtpSession", b =>
                {
                    b.Property<Guid>("OtpSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte>("OtpPurpose")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OtpSessionId");

                    b.HasIndex("HotelId");

                    b.ToTable("OtpSessions", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.PaymentOrder", b =>
                {
                    b.Property<long>("PaymentOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PaymentOrderId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GatewayOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("GatewayProvider")
                        .HasColumnType("smallint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaymentOrderId");

                    b.HasIndex("GatewayOrderId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("PaymentOrders", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.PaymentTransaction", b =>
                {
                    b.Property<long>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PaymentTransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("GatewayPaymentId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("PaymentOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text");

                    b.Property<string>("Signature")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<byte>("TransactionStatus")
                        .HasColumnType("smallint");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("GatewayPaymentId")
                        .IsUnique();

                    b.HasIndex("PaymentOrderId");

                    b.ToTable("PaymentTransactions", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.WebhookLog", b =>
                {
                    b.Property<long>("WebhookLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WebhookLogId"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("GatewayProvider")
                        .HasColumnType("smallint");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("RelatedOrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RelatedPaymentOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Signature")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("WebhookLogId");

                    b.HasIndex("GatewayProvider", "EventId")
                        .IsUnique();

                    b.ToTable("WebhookLogs", "public");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.GuestSession", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelRoomOrdering.Api.Domain.OtpSession", "OtpSession")
                        .WithMany()
                        .HasForeignKey("OtpSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("OtpSession");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Hotel", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelRoomOrdering.Api.Domain.Kitchen", "Kitchen")
                        .WithMany("Hotels")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Kitchen");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.HotelMenuItem", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.Hotel", "Hotel")
                        .WithMany("MenuItems")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelRoomOrdering.Api.Domain.Item", "Item")
                        .WithMany("HotelMenuItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Item", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Kitchen", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.City", "City")
                        .WithMany("Kitchens")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.KitchenItemAvailability", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelRoomOrdering.Api.Domain.Kitchen", "Kitchen")
                        .WithMany()
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Kitchen");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Order", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.GuestSession", "GuestSession")
                        .WithMany()
                        .HasForeignKey("GuestSessionId");

                    b.HasOne("HotelRoomOrdering.Api.Domain.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelRoomOrdering.Api.Domain.Kitchen", "Kitchen")
                        .WithMany()
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuestSession");

                    b.Navigation("Hotel");

                    b.Navigation("Kitchen");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.OrderLine", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelRoomOrdering.Api.Domain.Order", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.OrderStatusHistory", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.OtpSession", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.PaymentOrder", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.PaymentTransaction", b =>
                {
                    b.HasOne("HotelRoomOrdering.Api.Domain.PaymentOrder", "PaymentOrder")
                        .WithMany()
                        .HasForeignKey("PaymentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentOrder");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.City", b =>
                {
                    b.Navigation("Hotels");

                    b.Navigation("Kitchens");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Hotel", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Item", b =>
                {
                    b.Navigation("HotelMenuItems");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Kitchen", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("HotelRoomOrdering.Api.Domain.Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
